import "../globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="w-full bg-white justify-around flex h-[3rem] drop-shadow-md sticky top-0">
          <div className="grid w-[80%]">
            <div className="flex justify-between">
              <div className="pt-[.7rem]">TokoKu</div>
              <div className="flex space-around space-x-4">
                <div className="flex space-x-6 pt-[.7rem]">
                  <Link href="/">Home</Link>
                  <Link href="/product-user">Product</Link>
                </div>
                <div className="grid place-content-center bg-green">
                  <div className="bg-black px-[.7rem] py-[.1rem] rounded-full text-white text-[1rem] pt-[-.1rem]">
                    <Link href="/">LogOut</Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
